stages:
  - run

weekly_job:
  stage: run
  image: python:3.11-slim  
  variables:
    PYTHONUNBUFFERED: "1"
  script:
    # 1. Upgrade pip and install requirements directly into the container
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements.txt
    
    # 2. Run the actual script
    - echo "Running weekly job on Docker Linux..."
    - python main.py
  only:
    - schedules